### PR TITLE
Replaced ugly and broken Gradle project with working and clean Maven project.

### PR DESCRIPTION
**Pull request by mechite**
_**What I did**_
    Fixed readme markdown as it was malformed
    Switched to Maven because it is far superior to Gradle
    Made the import to jitpack for Maven work
_**How to compile the new version**_
    Git clone to a folder
    Install Maven
    Type "mvn install", or if there is already a target folder, "mvn clean install"
   There should be a compiled JAR in /target/AntiAntiDebug-1.0.8.jar

Maven is better than Gradle, stop using Gradle, stop using Gradle, s t o p  u s i n g  G r a d l e.

### CODE REVIEW

**Comment by xxDark** [comment]
Can you please tell what's wrong with the current Gradle build script?

**Comment by mechite** [comment]
Gradle is just bad.

**Comment by yeetyboi56-deprecated** [comment]
> Can you please tell what's wrong with the current Gradle build script?

I can't compile it because the build script is broken, maybe release the built jar?

**Comment by xxDark** [comment]
Can you please show me the error so I can fix it? Thanks.

**Comment by mechite** [comment]
The error is literally not present in the maven project, you could just
accept the pr :shrug:

>

**Pull request closed without merging**
